### ISSUE TITLE
Collapse Fields Button stop working

### ISSUE THREAD

**Issue by maev-mcbo** [clementlize/firestore-fullscreen#1]
i  guess because the firebase news and new features something has changed and the collapse fields button doesnt work anymore, entre/leave full screen and expand fields buttons still working.

**Comment by clementlize** [comment]
Hello! Thank you for submitting. What is your Firebase interface language?

The way I made the collapse/expand code would only make it work if the interface was in English. Someone reported this and I fixed it in the [latest release](https://github.com/clementlize/firestore-tools/releases/tag/v2.1.0) which will be available soon on the Chrome web store.

Please tell me in a few days if the new version (2.1.0) works for you. Thank you!

**Comment by maev-mcbo** [comment]
really? but my firebase is in spanish and always have worked, and now with the 2.1.0  seems that the issue has been resolved. all fields are expanding and collapsing, also the fullscreen is working too. thanks for such a awesome extension
